language: python
python:
  - "3.6"
node_js: 10
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run paver copy_secrets_file
  - npm --version
  - npm install
  - ./node_modules/.bin/webpack --version
script:
  - pytest
