language: python
python: "3.6"
node_js: 10
before_install:
  - npm i -g npm@6.4.1
install:
#  - pip install pipenv
#  - pipenv install --dev
#  - pipenv run paver copy_secrets_file
  - npm --version
  - npm install
  - ./node_modules/.bin/webpack --version
script:
  - pytest --version
